name: unit-tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Test
        run: |
          npm install
          npm run-script test

      - name: Uploade CodeCov Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
